### PR TITLE
Remove Python 2 compatibility code

### PR DESCRIPTION
**Pull request by kurtmckee**
As a side effect, the code coverage of unit tests is now 100%.

### CODE REVIEW

**Comment by kurtmckee** [comment]
Signed the Google CLA. Thanks for reviewing this PR!

I'm using this package in a project I'm working on, and I'm hopeful to add a few additional tests after this merges (specifically, I'd like to use Hypothesis to test the round-tripping functionality, as it is excellent at finding round-trip issues).

**Review by suminb — APPROVED** [review]
Looks good to me. Appreciate it!

**Comment by suminb** [comment]
I'll merge and publish this as v0.6.0 as soon as possible. Thanks for your PR!

**Comment by kurtmckee** [comment]
You're welcome! Thanks for your work on base62!

**Pull request merged**
